language: node_js
before_script:
  cd web
node_js:
  - 8
cache:
  directories:
    - web/node_modules
script:
  - npm install
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: hobby-matcher.surge.sh
  project: ./web/build/
  on:
    branch: develop
